[package]
name = "foolish-core"
version = "0.1.0"
edition = "2024"

[dependencies]
foolish-parser = { path = "../foolish-parser" }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }


[workspace.lints.rust]
unsafe_code = "warn"

[profile.release]
opt-level = 3
lto       = true
strip     = true
debug = 0

[profile.dev]
codegen-units = 256
debug = 1
opt-level = 0

[profile.test]
opt-level = 1           # Slightly optimize tests for faster execution
debug = 1
debug-assertions = true # Keep safety checks enabled
