[workspace]
members = [
    "foolish-parser",
    "foolish-core",
    "foolish-cli",
    "foolish-web",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
regex = "1"
anyhow = "1"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
insta = { version = "1", features = ["yaml"] }
