[workspace]
members = [
    "foolish-parser",
    "foolish-core",
    "foolish-cli",
    "foolish-web",
    "foolish-ubcb",
    "foolish-ubcb-cli",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
regex = "1"
anyhow = "1"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
insta = { version = "1", features = ["yaml"] }

[workspace.lints.rust]
unsafe_code = "warn"

[profile.release]
opt-level = 3
lto       = true
strip     = true
debug = 0

[profile.dev]
codegen-units = 256
debug = 1
opt-level = 0

[profile.test]
opt-level = 1           # Slightly optimize tests for faster execution
debug = 1
debug-assertions = true # Keep safety checks enabled
