[package]
name = "foolish-web"
version = "0.1.0"
edition = "2024"

[dependencies]
foolish-core = { path = "../foolish-core" }
axum = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }

[workspace.lints.rust]
unsafe_code = "warn"

[profile.release]
opt-level = 3
lto       = true
strip     = true
debug = 0

[profile.dev]
codegen-units = 256
debug = 1
opt-level = 0

[profile.test]
opt-level = 1           # Slightly optimize tests for faster execution
debug = 1
debug-assertions = true # Keep safety checks enabled
