[package]
name = "foolish-ubca"
version = "0.1.0"
edition = "2024"

[dependencies]
foolish-core = { path = "../foolish-core" }
foolish-parser = { path = "../foolish-parser" }
anyhow = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
num_cpus = "1"

[lints.rust]
unsafe_code = "warn"
