[package]
name = "foolish-ubcb-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "foolish-ubcb-cli"
path = "src/main.rs"

[dependencies]
foolish-core = { path = "../foolish-core" }
foolish-ubcb = { path = "../foolish-ubcb" }
clap = { workspace = true }
anyhow = { workspace = true }
insta = { workspace = true }
rayon = "1"

[lib]
name = "foolish_ubcb_cli"
path = "src/lib.rs"

[dev-dependencies]
insta = { workspace = true }
rayon = "1"
num_cpus = "1"

[lints.rust]
unsafe_code = "warn"
