//! The four-stage lifecycle and stage-directory operations (FOOP-92 §3).

use std::path::{Path, PathBuf};

use crate::error::{EinmoError, Result};

/// One of the four promotion stages. Each maps to a directory that mirrors the
/// `input/` tree.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Stage {
    /// Generated by the test runner. Carries `compiled` + `configured` +
    /// `stage:output` stamps.
    Output,
    /// Reviewed — promoted from `output` by an AI agent or human. Adds a
    /// `stage:checked` stamp.
    Checked,
    /// Set aside — any state → flagged via CLI (move, advisory line, no stamp).
    /// A terminal sink.
    Flagged,
    /// Promoted from `checked` (or `output`) by a human with a passphrase.
    /// Adds a `stage:verified` stamp.
    Verified,
}

impl Stage {
    /// All four stages, in lifecycle order.
    pub const ALL: [Stage; 4] = [
        Stage::Output,
        Stage::Checked,
        Stage::Flagged,
        Stage::Verified,
    ];

    /// The default directory name for this stage.
    #[must_use]
    pub fn dir_name(self) -> &'static str {
        match self {
            Stage::Output => "output",
            Stage::Checked => "checked",
            Stage::Flagged => "flagged",
            Stage::Verified => "verified",
        }
    }

    /// The `stage:<name>` stamp key this stage appends on promotion.
    #[must_use]
    pub fn stamp_key(self) -> &'static str {
        match self {
            Stage::Output => "stage:output",
            Stage::Checked => "stage:checked",
            Stage::Flagged => "stage:flagged",
            Stage::Verified => "stage:verified",
        }
    }

    /// Parse a stage from its lowercase directory name.
    ///
    /// # Errors
    ///
    /// Returns [`EinmoError::InvalidStageName`] for any unrecognized name.
    pub fn parse(name: &str) -> Result<Self> {
        match name {
            "output" => Ok(Stage::Output),
            "checked" => Ok(Stage::Checked),
            "flagged" => Ok(Stage::Flagged),
            "verified" => Ok(Stage::Verified),
            other => Err(EinmoError::InvalidStageName(other.to_string())),
        }
    }
}

impl std::fmt::Display for Stage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.dir_name())
    }
}

/// Validate a stage or stage-directory name against `[A-Za-z0-9_-]+`.
///
/// # Errors
///
/// Returns [`EinmoError::InvalidStageName`] if the name is empty or contains
/// any character outside the allowed set.
pub fn validate_stage_name(name: &str) -> Result<()> {
    if !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        Ok(())
    } else {
        Err(EinmoError::InvalidStageName(name.to_string()))
    }
}

/// Map an input-relative path to its mirror-relative `.einmo` path.
///
/// `stage1/section3/specific.foo` → `stage1/section3/specific.foo.einmo`.
/// Discovery is extension-agnostic — any file under `input/` is a test
/// trigger, so `.foo`, `.py`, and `.js` all map by appending `.einmo`.
#[must_use]
pub fn mirror_input_path(input_rel: &Path) -> PathBuf {
    let mut os = input_rel.as_os_str().to_os_string();
    os.push(".einmo");
    PathBuf::from(os)
}

/// Recursively discover every file under `input_dir`, returning
/// input-relative paths in sorted (deterministic) order.
///
/// `depth_limit` caps the recursion depth (catches symlink cycles); pass
/// [`MAX_WALK_DEPTH`] for the default.
///
/// # Errors
///
/// Returns [`EinmoError::Io`] if the tree cannot be walked.
pub fn walk_input_tree(input_dir: &Path, depth_limit: usize) -> Result<Vec<PathBuf>> {
    Ok(walk_input_tree_reporting(input_dir, depth_limit)?.0)
}

/// As [`walk_input_tree`], but also returns the **extraneous** entries it
/// refused to treat as inputs (dot-prefixed files and directories).
///
/// Discovery skips them so an open editor cannot inject phantom tests; this
/// variant hands them back so the caller can *report* them. Einmo never
/// silently ignores a file in its own tree — a suite whose shape is wrong is a
/// failure, not a detail.
///
/// # Errors
///
/// Returns [`EinmoError::Io`] if the tree cannot be walked.
pub fn walk_input_tree_reporting(
    input_dir: &Path,
    depth_limit: usize,
) -> Result<(Vec<PathBuf>, Vec<PathBuf>)> {
    let mut found = Vec::new();
    let mut extraneous = Vec::new();
    walk_dir_depth(
        input_dir,
        input_dir,
        &mut found,
        &mut extraneous,
        0,
        depth_limit,
    )?;
    found.sort();
    extraneous.sort();
    Ok((found, extraneous))
}

/// Maximum recursion depth for the directory walk. Catches pathologically deep
/// trees as well as symlink cycles (a symlink cycle would otherwise recurse
/// forever). This is the default used by [`TestConfig::new`](crate::config::TestConfig::new).
pub(crate) const MAX_WALK_DEPTH: usize = 64;

fn walk_dir_depth(
    root: &Path,
    dir: &Path,
    out: &mut Vec<PathBuf>,
    extraneous: &mut Vec<PathBuf>,
    depth: usize,
    depth_limit: usize,
) -> Result<()> {
    if depth > depth_limit {
        return Err(EinmoError::Io {
            path: dir.to_path_buf(),
            source: std::io::Error::other(format!(
                "directory walk exceeded max depth {depth_limit} (possible symlink cycle)"
            )),
        });
    }
    if !dir.exists() {
        return Ok(());
    }
    let entries = std::fs::read_dir(dir).map_err(|e| EinmoError::io(dir, e))?;
    for entry in entries {
        let entry = entry.map_err(|e| EinmoError::io(dir, e))?;
        let path = entry.path();
        // Dot-prefixed entries (editor swap files, `.git`, `.DS_Store`) are
        // never test inputs: a test input is a file someone deliberately named.
        // They are skipped for *discovery* — an open editor must not inject
        // phantom tests — but recorded as extraneous so the caller can report
        // them. Einmo never silently ignores a file in its own tree.
        if entry
            .file_name()
            .to_str()
            .is_some_and(|n| n.starts_with('.'))
        {
            if let Ok(rel) = path.strip_prefix(root) {
                extraneous.push(rel.to_path_buf());
            }
            continue;
        }
        let file_type = entry.file_type().map_err(|e| EinmoError::io(&path, e))?;
        if file_type.is_symlink() {
            // Follow the symlink to determine the target type. A broken
            // symlink (target missing → NotFound) is skipped silently — it is
            // not a valid test input. Other metadata failures (e.g. ELOOP
            // from a symlink cycle) are propagated as errors.
            let metadata = match std::fs::metadata(&path) {
                Ok(m) => m,
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => continue,
                Err(e) => return Err(EinmoError::io(&path, e)),
            };
            if metadata.is_dir() {
                walk_dir_depth(root, &path, out, extraneous, depth + 1, depth_limit)?;
            } else if metadata.is_file() {
                let rel = path
                    .strip_prefix(root)
                    .map_err(|_| EinmoError::Io {
                        path: path.clone(),
                        source: std::io::Error::other("path not under input root"),
                    })?
                    .to_path_buf();
                out.push(rel);
            }
        } else if file_type.is_dir() {
            walk_dir_depth(root, &path, out, extraneous, depth + 1, depth_limit)?;
        } else if file_type.is_file() {
            let rel = path
                .strip_prefix(root)
                .map_err(|_| EinmoError::Io {
                    path: path.clone(),
                    source: std::io::Error::other("path not under input root"),
                })?
                .to_path_buf();
            out.push(rel);
        }
    }
    Ok(())
}

/// Ensure the parent directory of `path` exists (creating the mirrored subtree
/// on demand).
///
/// # Errors
///
/// Returns [`EinmoError::Io`] if directory creation fails.
pub fn ensure_parent_dir(path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| EinmoError::io(parent, e))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn stage_names_and_stamp_keys() {
        assert_eq!(Stage::Output.dir_name(), "output");
        assert_eq!(Stage::Verified.stamp_key(), "stage:verified");
        assert_eq!(Stage::parse("checked").unwrap(), Stage::Checked);
        assert!(Stage::parse("bogus").is_err());
    }

    #[test]
    fn validate_stage_name_rules() {
        assert!(validate_stage_name("output").is_ok());
        assert!(validate_stage_name("output-2").is_ok());
        assert!(validate_stage_name("out_put").is_ok());
        assert!(validate_stage_name("").is_err());
        assert!(validate_stage_name("out>put").is_err());
        assert!(validate_stage_name("out put").is_err());
    }

    #[test]
    fn flat_input_maps_to_flat_mirror() {
        assert_eq!(
            mirror_input_path(Path::new("simple.foo")),
            PathBuf::from("simple.foo.einmo")
        );
    }

    #[test]
    fn hierarchical_input_maps_to_mirrored_path() {
        assert_eq!(
            mirror_input_path(Path::new("stage1/section3/specific.foo")),
            PathBuf::from("stage1/section3/specific.foo.einmo")
        );
    }

    #[test]
    fn non_foo_extensions_discovered() {
        let tmp = tempfile::tempdir().unwrap();
        let input = tmp.path().join("input");
        fs::create_dir_all(input.join("nested")).unwrap();
        fs::write(input.join("a.py"), "1+2").unwrap();
        fs::write(input.join("nested/b.js"), "1+2").unwrap();
        fs::write(input.join("nested/c.foo"), "{3;}").unwrap();

        let found = walk_input_tree(&input, MAX_WALK_DEPTH).unwrap();
        assert_eq!(
            found,
            vec![
                PathBuf::from("a.py"),
                PathBuf::from("nested/b.js"),
                PathBuf::from("nested/c.foo"),
            ]
        );
    }

    #[test]
    fn same_basename_different_branches_coexist() {
        let a = mirror_input_path(Path::new("x/test.foo"));
        let b = mirror_input_path(Path::new("y/test.foo"));
        assert_ne!(a, b);
        assert_eq!(a, PathBuf::from("x/test.foo.einmo"));
        assert_eq!(b, PathBuf::from("y/test.foo.einmo"));
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_file_discovered() {
        use std::os::unix::fs::symlink;
        let tmp = tempfile::tempdir().unwrap();
        let input = tmp.path().join("input");
        fs::create_dir_all(&input).unwrap();
        fs::write(input.join("real.py"), "1+2").unwrap();
        symlink(input.join("real.py"), input.join("link.py")).unwrap();

        let found = walk_input_tree(&input, MAX_WALK_DEPTH).unwrap();
        let names: Vec<String> = found
            .iter()
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        assert!(names.contains(&"real.py".to_string()));
        assert!(names.contains(&"link.py".to_string()));
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_dir_recursed() {
        use std::os::unix::fs::symlink;
        let tmp = tempfile::tempdir().unwrap();
        let input = tmp.path().join("input");
        let real_dir = input.join("real_dir");
        fs::create_dir_all(&real_dir).unwrap();
        fs::write(real_dir.join("inside.foo"), "{3;}").unwrap();
        symlink(&real_dir, input.join("link_dir")).unwrap();

        let found = walk_input_tree(&input, MAX_WALK_DEPTH).unwrap();
        assert!(
            found
                .iter()
                .any(|p| p == &PathBuf::from("link_dir/inside.foo")),
            "file inside symlinked dir not discovered: {found:?}"
        );
    }

    #[cfg(unix)]
    /// An editor swap file (or any dot-prefixed entry) is not a test input:
    /// an open vim session must not inject phantom tests into the suite.
    #[test]
    fn walk_skips_hidden_entries() {
        let tmp = tempfile::tempdir().unwrap();
        let input = tmp.path().join("input");
        std::fs::create_dir_all(input.join("foop/13")).unwrap();
        std::fs::write(input.join("foop/13/comprehensive.foo"), "{1;}").unwrap();
        std::fs::write(input.join("foop/13/.comprehensive.foo.swp"), "vim").unwrap();
        std::fs::create_dir_all(input.join(".git")).unwrap();
        std::fs::write(input.join(".git/config"), "x").unwrap();

        let found = walk_input_tree(&input, MAX_WALK_DEPTH).unwrap();
        assert_eq!(
            found,
            vec![PathBuf::from("foop/13/comprehensive.foo")],
            "hidden files and dot-directories must not be discovered as inputs"
        );
    }

    #[test]
    fn walk_depth_limit_prevents_infinite_symlink_cycle() {
        use std::os::unix::fs::symlink;
        let tmp = tempfile::tempdir().unwrap();
        let input = tmp.path().join("input");
        fs::create_dir_all(&input).unwrap();
        // A symlink cycle: a -> b -> a. Following either link hits ELOOP,
        // which the walker propagates as an error rather than hanging.
        symlink(input.join("b"), input.join("a")).unwrap();
        symlink(input.join("a"), input.join("b")).unwrap();

        let result = walk_input_tree(&input, MAX_WALK_DEPTH);
        assert!(
            result.is_err(),
            "expected walk of symlink cycle to error, got {result:?}"
        );
    }
}
